# Generated by Django 3.0 on 2019-12-09 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakopane_weather.Day')),
            ],
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('phrase', models.CharField(max_length=150)),
                ('probability', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakopane_weather.Day')),
            ],
        ),
    ]
