# Generated by Django 3.0 on 2020-03-11 14:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('phrase', models.CharField(max_length=150)),
                ('probability', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('real_feel_temp', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('rain_probability', models.IntegerField()),
                ('cloud_cover', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_peak', models.CharField(default='Random Peak', max_length=50)),
                ('elevation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OctaveOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('octave_of_a_day', models.CharField(max_length=50)),
                ('wind_speed', models.IntegerField()),
                ('summary', models.CharField(max_length=50)),
                ('rain', models.IntegerField()),
                ('snow', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('chill_temperature', models.IntegerField()),
                ('name_of_peak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zakopane_weather.Mountain')),
            ],
        ),
    ]
