# Generated by Django 3.0 on 2020-03-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='octaveofday',
            old_name='wind_speed',
            new_name='windspeed',
        ),
    ]
