# Generated by Django 3.0 on 2019-12-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0002_auto_20191210_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyforecast',
            name='probability',
            field=models.FloatField(),
        ),
    ]
