# Generated by Django 3.0 on 2019-12-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0003_auto_20191211_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourlyforecast',
            old_name='max_temp',
            new_name='cloud_cover',
        ),
        migrations.RenameField(
            model_name='hourlyforecast',
            old_name='min_temp',
            new_name='rain_probability',
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='real_feel_temp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='temp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='wind_speed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='probability',
            field=models.IntegerField(),
        ),
    ]
