# Generated by Django 3.0 on 2020-03-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0003_auto_20200315_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvalancheStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avalanche_level', models.IntegerField()),
                ('avalanche_description', models.CharField(max_length=200)),
                ('avalanche_warning_published', models.DateTimeField()),
                ('avalanche_warning_valid_until', models.DateTimeField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='octaveofday',
            name='summary',
            field=models.CharField(max_length=500),
        ),
    ]
