# Generated by Django 3.0 on 2020-03-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0004_auto_20200320_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalanchestatus',
            name='avalanche_description',
            field=models.CharField(max_length=1500),
        ),
    ]
