# Generated by Django 3.0 on 2020-03-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0005_mountain_octaveofday'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='avalanche',
            field=models.IntegerField(default=0),
        ),
    ]
