# Generated by Django 3.0 on 2020-04-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0005_auto_20200326_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='octaveofday',
            name='octave_of_a_day',
        ),
        migrations.AlterField(
            model_name='octaveofday',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
