# Generated by Django 3.0 on 2020-04-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0006_auto_20200401_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaWeatherForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('temp_min', models.IntegerField()),
                ('temp_max', models.IntegerField()),
                ('pressure', models.FloatField()),
                ('rain', models.FloatField()),
            ],
        ),
    ]
