# Generated by Django 3.0 on 2020-06-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0007_areaweatherforecast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='octaveofday',
            name='name_of_peak',
        ),
    ]
