# Generated by Django 3.0 on 2020-06-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0008_remove_octaveofday_name_of_peak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mountain',
        ),
    ]
