# Generated by Django 3.0 on 2020-06-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0009_delete_mountain'),
    ]

    operations = [
        migrations.AddField(
            model_name='octaveofday',
            name='elevation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='octaveofday',
            name='name',
            field=models.CharField(default='Random Peak', max_length=50),
        ),
    ]
