# Generated by Django 3.0 on 2020-06-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0010_auto_20200604_0743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OctaveOfDay',
            new_name='PeakForecast',
        ),
    ]
