# Generated by Django 3.0 on 2020-06-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0012_auto_20200604_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaweatherforecast',
            name='summary',
            field=models.CharField(default='brak informacji', max_length=60),
        ),
    ]
