# Generated by Django 3.0 on 2020-06-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakopane_weather', '0013_areaweatherforecast_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaweatherforecast',
            name='icon_number',
            field=models.IntegerField(default=4),
        ),
    ]
