# Generated by Django 3.0 on 2020-05-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20200521_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='icon-user.png', upload_to='profile_picture'),
        ),
    ]
