# Generated by Django 3.0 on 2020-06-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20200521_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='post',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
