version: "3"

services: 
    app:
        build: 
            context: .
        volumes: 
            - .:/app
        env_file: .env
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        depends_on: 
            - postgres
    
    postgres:
        image: postgres:12.2-alpine
        
        ports: 
            - "5432:5432"
        env_file: .env